[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["./generate-play-previews.sh"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false

[watch]
watch = [
    ".",
    "../src",
    "../Cargo.toml",
    "../../src",
    "../../Cargo.toml",
    "../../Cargo.lock",
    "../../mirx/src",
    "../../mirx/Cargo.toml",
    "../../mirui-macros/src",
    "../../mirui-macros/Cargo.toml",
]
ignore = ["dist"]
