#!/usr/bin/env python3

import argparse
import json
from pathlib import Path


TWIN_CELL = {".": 0, "#": 1, "D": 2}
FOLD_CELL = {".": 0, "#": 1, "F": 2, "B": 3, "S": 4}


def pack(values, bits):
    output = bytearray((len(values) * bits + 7) // 8)
    mask = (1 << bits) - 1
    for index, value in enumerate(values):
        if value < 0 or value > mask:
            raise ValueError(f"value {value} does not fit in {bits} bits")
        bit = index * bits
        output[bit // 8] |= (value & mask) << (bit % 8) & 0xFF
        if bit % 8 + bits > 8:
            output[bit // 8 + 1] |= value >> (8 - bit % 8)
    return bytes(output)


def rust_bytes(name, values):
    lines = [f"pub(super) static {name}: [u8; {len(values)}] = ["]
    for offset in range(0, len(values), 20):
        chunk = ", ".join(str(value) for value in values[offset : offset + 20])
        lines.append(f"    {chunk},")
    lines.append("];")
    return "\n".join(lines)


def generate(source):
    if source["version"] != "expeditions-05.1":
        raise ValueError("unexpected campaign version")
    for key in ("twin", "fold", "pic"):
        if len(source[key]) != 36:
            raise ValueError(f"{key} must contain 36 levels")

    twin_maps = bytearray()
    twin_solutions = bytearray()
    twin_rows = []
    for index, level in enumerate(source["twin"]):
        if level["w"] != 6 or level["h"] != 6:
            raise ValueError(f"twin {index} has invalid dimensions")
        cells = [TWIN_CELL[cell] for board in level["maps"] for cell in board]
        if len(cells) != 72:
            raise ValueError(f"twin {index} has invalid maps")
        map_offset = len(twin_maps)
        twin_maps.extend(pack(cells, 2))
        solution_offset = len(twin_solutions)
        solution = level["solution"]
        twin_solutions.extend(pack(solution, 2))
        key = 255 if level["key"] is None else level["key"][1]
        twin_rows.append(
            "    TwinLevelData { "
            f"mode: {level['mode']}, starts: {level['starts']}, goals: {level['goals']}, "
            f"key: {key}, par: {level['par']}, map_offset: {map_offset}, "
            f"solution_offset: {solution_offset}, solution_len: {len(solution)} "
            "},"
        )

    fold_maps = bytearray()
    fold_solutions = bytearray()
    fold_rows = []
    for index, level in enumerate(source["fold"]):
        if level["w"] != 10 or level["h"] != 7:
            raise ValueError(f"fold {index} has invalid dimensions")
        cells = [FOLD_CELL[cell] for cell in level["map"]]
        if len(cells) != 70:
            raise ValueError(f"fold {index} has invalid map")
        map_offset = len(fold_maps)
        fold_maps.extend(pack(cells, 3))
        solution_offset = len(fold_solutions)
        solution = level["solution"]
        fold_solutions.extend(pack(solution, 2))
        seals = list(level["seals"])
        if len(seals) > 2:
            raise ValueError(f"fold {index} has too many seals")
        seals.extend([255] * (2 - len(seals)))
        fold_rows.append(
            "    FoldLevelData { "
            f"start: {level['start']}, goal: {level['goal']}, seals: {seals}, "
            f"seal_count: {len(level['seals'])}, par: {level['par']}, map_offset: {map_offset}, "
            f"solution_offset: {solution_offset}, solution_len: {len(solution)} "
            "},"
        )

    picture_images = bytearray()
    picture_rows = []
    for index, level in enumerate(source["pic"]):
        n = level["n"]
        if n < 5 or n > 10 or len(level["image"]) != n * n:
            raise ValueError(f"picture {index} has invalid dimensions")
        image_offset = len(picture_images)
        picture_images.extend(pack(level["image"], 1))
        givens = list(level["givens"])
        if len(givens) > 2:
            raise ValueError(f"picture {index} has too many givens")
        given_cells = [entry[0] for entry in givens]
        given_values = sum((entry[1] & 1) << bit for bit, entry in enumerate(givens))
        given_cells.extend([255] * (2 - len(given_cells)))
        picture_rows.append(
            "    PictureLevelData { "
            f"size: {n}, image_offset: {image_offset}, givens: {given_cells}, "
            f"given_values: {given_values}, given_count: {len(givens)} "
            "},"
        )

    parts = [
        "// @generated by gallery/examples/tools/generate_expeditions_data.py",
        "// Source campaign: expeditions-05.1",
        "",
        "use super::expeditions::{FoldLevelData, PictureLevelData, TwinLevelData};",
        "",
        rust_bytes("TWIN_MAPS", twin_maps),
        "",
        rust_bytes("TWIN_SOLUTIONS", twin_solutions),
        "",
        "pub(super) static TWIN_LEVELS: [TwinLevelData; 36] = [",
        *twin_rows,
        "];",
        "",
        rust_bytes("FOLD_MAPS", fold_maps),
        "",
        rust_bytes("FOLD_SOLUTIONS", fold_solutions),
        "",
        "pub(super) static FOLD_LEVELS: [FoldLevelData; 36] = [",
        *fold_rows,
        "];",
        "",
        rust_bytes("PICTURE_IMAGES", picture_images),
        "",
        "pub(super) static PICTURE_LEVELS: [PictureLevelData; 36] = [",
        *picture_rows,
        "];",
        "",
    ]
    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    source = json.loads(args.source.read_text(encoding="utf-8"))
    args.output.write_text(generate(source), encoding="utf-8")


if __name__ == "__main__":
    main()
